name: build-win
# copied from /stock-synthesis/build-win.yml created by Kathryn Doering

# Controls when the action will run.
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-win"
  build-win:
    # The type of runner that the job will run on
    runs-on: windows-2019
    # Limit run time to 15 min to avoid wasting action minutes.
    timeout-minutes: 15
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get admb and put in path
        run: |
          Invoke-WebRequest -Uri https://github.com/admb-project/admb/releases/download/admb-12.3/admb-12.3-windows.zip -OutFile "D:\a\nwfscAgeingError\nwfscAgeingError\admb-12.3.zip"
          Expand-Archive -LiteralPath "D:\a\nwfscAgeingError\nwfscAgeingError\admb-12.3.zip" -DestinationPath "D:\a\nwfscAgeingError\nwfscAgeingError\"
          echo "D:\a\nwfscAgeingError\nwfscAgeingError\admb-12.3\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build ADMB executable
        run: |
          cd src
          admb agemat

      - name: Archive windows exes
        if: success()
        uses: actions/upload-artifact@main
        with:
          name: 'agemat_win_exes'
          path: src/
