name: build-centos
# copied from /stock-synthesis/build-centos.yml created by Kathryn Doering

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-centos:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    # Limit run time to 15 min to avoid wasting action minutes.
    timeout-minutes: 15
    container: 
      image: centos:7.8.2003
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get essential tools needed on docker
        run: |
         yum -y update && yum clean all
         yum -y install wget
         yum install -y zip unzip
         yum install -y sudo
         yum install -y gcc-c++
      - name: Get admb and put in path
        run: |
          wget https://github.com/admb-project/admb/releases/download/admb-12.2/admb-12.2-linux.zip
          sudo unzip admb-12.2-linux.zip -d /usr/local/bin
          sudo chmod 755 /usr/local/bin/admb-12.2/bin/admb
          echo "/usr/local/bin/admb-12.2/bin" >> $GITHUB_PATH
          
      # Runs a set of commands using the runners shell
      - name: Build ADMB executable
        run: |
          cd src
          /bin/bash admb agemat
          
      - name: Archive the exes as tar.
        if: success()
        uses: actions/upload-artifact@main
        with:
          name: agemat_linux
          path: exes/
