name: build-mac
# copied from /stock-synthesis/build-mac.yml created by Kathryn Doering

# on: Controls when the action will run. workflow_dispatch is a manual trigger.
on: workflow_dispatch

jobs:
  build-mac:
    runs-on: macos-10.15
    # Limit run time to 15 min to avoid wasting action minutes.
    timeout-minutes: 15
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get admb and put in path
        run: |
          curl https://github.com/admb-project/admb/releases/download/admb-12.2/admb-12.2-macos-xcode12.zip -L -o admb-12.2.zip
          unzip admb-12.2.zip -d /usr/local/bin
          ls /usr/local/bin
          echo "/usr/local/bin/admb-12.2/bin" >> $GITHUB_PATH
          
      - name: Build ADMB executable
        run: |
          cd src
          /bin/bash admb agemat

      - name: Delete unneeded files
        run: |
          rm *.obj *.htp *.cpp
					
      - name: Archive the binaries
        if: success()
        uses: actions/upload-artifact@main
        with:
          name: agemat_osx
          path: src/
